# write action that on master push: pulls changes, runs wasm-pack build --target web and pushes pkg to gh-pages branch
name: wasm-pages

on:
    push:
        branches:
            - master

jobs:
    wasm-pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - name: Build
              run: wasm-pack build --target web
            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v4
              with:
                target_branch: gh-pages
                build_dir: pkg
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}