name: wasm-pages

on:
    push:
        branches:
            - master

jobs:
    wasm-pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
              with:
                ref: gh-pages
            - name: configure git
              run: git config user.name GitHub && git config user.email noreply@github.com
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - name: Build
              run: wasm-pack build --target web
            - name: add
              run: git add -f pkg
            - name: commit
              run : git commit -m "Auto wasm"
            - name: Commit and push changes to gh-pages
              run: |
                git checkout --orphan gh-pages
                git rm -rf .
                cp -a ./dist/. .
                git add -A
                git commit -m "Deploy to gh-pages"
                git push origin gh-pages --force