# write action that on master push: pulls changes, runs wasm-pack build --target web and pushes pkg to gh-pages branch
name: wasm-pages

on:
    push:
        branches:
            - master

jobs:
    wasm-pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - name: Build
              run: wasm-pack build --target web
            - name: configure git
              run: git config user.name GitHub && git config user.email noreply@github.com
            - name: add
              run: git add -f pkg
            - name: commit
              run : git commit -m "Auto pkg"
            - name: push
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: "gh-pages"